language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "tTowUhV+EtDhd62a8lZGHpoYsp9pxSV5GEFSt1v0jZQyBlJq+jkTnQuf/wK7WNa8wquvNBk61/TGhxEdunkOGIEelJ2sQ+Vsh+q/4uC+dlDneXPPa+PDKowI4XHMxuKBE6LcR9cBvQQsqdf4umkEhhNyUlF6+SznGADiJ49m+Ajp9woda0/N1wsQb/4EMItc83J2yn72Ye5hEywWaqMcqYFzmDC0oN2kVAU7ezvRD6xaPW28ODx304kL5z/o9rEqTadD+hKpBduzSe5N9U6fsmIeoxnV6dssmMf4X5kWw63A42Ys1D5WNeB3YPKfiTqu74C/XTqR0g6HtdhLm23UkCPI4V1JTgbTxqPslBr/yEBG3gRVMxv9uwN6zP32MwxeC+zyN68zuL3aZNmF8ndogsoJWNXl1PrDFQ0Vw02YsNh0RKfaLz8QxChrYCDUfJG5gFzRyY5UKdeMVwrKrEBGsyL3awAX89cDsAXYKnAyiUqZqlMytNQcyzQ5y2ecDpxOtaBwz+oULd/6kjMuqnXsCKmmwvrmd+vQVCYRZ7oPHHALzKAPz0/OQk0rC0qhKC8p/GvUaA60VACMH+CvWdBezBRfuCHAu50Om3P7IoXDATWphgJvzcFE7KTI+QJ8WqWt09Qs/F+fRgakh12maEKemXyPrqzWfHsE9AQ+o1rj+xA="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/com/r2cloud/

