language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token: 
      secure: "WM/aNKSiE8WhzGzG4yovbwaT+gU9+kKt/i8X7yX2y4hsUTN9FvEFnNVAAi6HiVwIlb5DZd6KzJdSqRvQp+I29brn+RN6RHLNFzgBybMhniqqmvaylcZyxprmjvwMQNUSwJ7QIzAsZ0lFkv0FInss7yWKDE6x7Z3rZl2Ia/lvU1gDxhS9ZaX09LqkhhWp2oNZ5HFN7AzWJ9kqkOgRFM8ZgYWDYcqzdF6Q+5yiTDiJ2xTlp4CIUV9dB4RyC2YfYNGy0jE+y+DGGnl9rmmRB7KDjuNin1U9SRFkeJ274+qlU9++5k6TA8fltLCqckP1uifPMccURjUZg9Ze33F0jCnxXUtII87tRDPfLjS4n3c+BYjbo99gm40yfOQBUQQOkglJbv6YDY7mzFyo7o5KBQkE+5WgNTVQ7MYvuIukHMVnmDGjw3Nbe9W9+Y7Ob9ChG9h4dlT/e0k8AD141pYLzXOekI8DvRcJWuNOv2FCiKR1SoSiQwnCXAuDRjG3i2d89zpvAgVzUSOGRaBkae9NJD9FJsHCCwvx+69NQZyHtjyHpprSPl5uY7L+tER844spt6ru5oOI03YcMWxAMoDuMyEgbn71IN2TdaM18KYm7/6b5m0nV0KxQIWR+1TUpccTU9+kigVY0kCHyJAGM9JWBuNjgVwjoxWOWE7wk7c+++g7ymY="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java -Dsonar.projectKey=dernasherbrezon_apt-html

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/com/r2cloud/

