language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token: 
      secure: "MuCEHDu6GDE+8XsRlTCdElpu9E91OE5SSEjU1MdpU8n5dUcM0UDgefODyIjIvMi1nptYuek2XGu3+vtBIt1Yk4rV7XgMTS9SYHQjDZ6sCYuwYVKGqGYmBtMLnMKGKpJ1LRrI1xfJ/5KY7VuviFhQ5ac1T4pe7c3jNnIITS6/DU8o+lsIwoairG7YDJxJtVQ/hEbhz9Bl/Z0Kk0pKXC2aM7bIJfjM51PkGWGj9MSLl/1C0QN3eiwCMn0gN7lmrgqtd27SimbQpxPiKoxccJcdl7iqlChy1+c2bVCsErc9D4HnWS/F+kp33fFoueQUXIszsnHQZ8zrBmwTN3r25lIbZDD6q+GvlRRr4K2KjH0myAmac8Ij318XZO61Yju+wsLQKGR1adqgzq45+Vh+br6AXhSgKQbWCqOKLkKpbm8VHV5tSLwBC/vO99HtSNDGbI9PNUsFOu7F8E/l1DzZG/UenAnZWM4pMwUyLBGlRSSQT8M16sH6PJP9Vy/T1Upgidar7/L5F7KOUCc1VwYlST/WOzsUjX+QQ89Z1YL06IB/nVL5ahlPgP+3A953918TCMeK1zHV+9GJPOBBw1ZgGr5whrqwipMHk8CJwtVX5U322IFZFBwUZaMgUISIiUzqTzb0b0VBqqh7O1MUVlkCUfD0wGhidLEfU1Tc16jOeCeOQcE="

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/com/r2cloud/

